# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"  # Vite 默认输出目录
  functions = "netlify/functions"  # 如需 serverless 函数

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false  # 解决 SPA 路由刷新 404 问题
